name: Casual Chat WebApp CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check-env:
    name: Check Environment
    runs-on: self-hosted
    steps:
      - name: Verify make Installment
        run: make -version
      
      - name: Verify node Installment
        run: node -v
      
      - name: Verify npm Installment
        run: npm -v
      
      - name: Verify xunit-viewer Installment
        run: xunit-viewer --version

  check-style:
    name: Check Webapp Style
    runs-on: self-hosted
    needs: [ check-env ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      
      - name: Install Dependency
        run: npm ci
      
      - name: Check Style
        run: npm run check

  check-i18n:
    name: Check Webapp I18n
    runs-on: self-hosted
    needs: [ check-env ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      
      - name: Install Dependency
        run: npm ci
      
      - name: Check I18n
        run: |
          cp i18n/en.json /tmp/en.json
          mkdir -p /tmp/fake-mobile-dir/assets/base/i18n/
          echo '{}' > /tmp/fake-mobile-dir/assets/base/i18n/en.json
          npm run mmjstool -- i18n extract-webapp --webapp-dir . --mobile-dir /tmp/fake-mobile-dir
          diff /tmp/en.json i18n/en.json 
          npm run mmjstool -- i18n clean-empty --webapp-dir . --mobile-dir /tmp/fake-mobile-dir --check
          rm -rf tmp

  check-type:
    name: Check Webapp Type
    runs-on: self-hosted
    needs: [ check-env ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      
      - name: Install Dependency
        run: npm ci
      
      - name: Check Type
        run: npm run check-types

  test-webapp:
    name: Test Webapp
    runs-on: self-hosted
    needs: [ check-style , check-type , check-i18n ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      
      - name: Install Dependency
        run: npm ci
      
      - name: Test
        run: npm run test-ci 
      
      - name: Check Xml Test Report
        id: find_test_report
        run: test -f build/test-results.xml
        if: always()

      - name: Generate HTML Report
        run: xunit-viewer -r build/test-results.xml -o build/test-results.html
        if: steps.find_test_report.outcome == 'success'
      
      - name: Upload Test Report
        uses: actions/upload-artifact@v2
        if: steps.find_test_report.outcome == 'success'
        with:
          name: webapp-test-results-${{ github.run_id }}
          path: |
            build/test-results.xml
            build/test-results.html

  build:
    name: Build Webapp
    runs-on: self-hosted
    needs: [ test-webapp ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      
      - name: Install Dependency
        run: |
          npm ci
          cd node_modules/mattermost-redux && npm i && npm run build
      
      - name: Build
        run: npm run build 

      - name: Upload Webapp
        uses: actions/upload-artifact@v2
        with:
          name: casualchat-mattermost-webapp-${{ github.run_number }}
          path: dist/
